### ISSUE TITLE
vlan access on lag Interface

### ISSUE THREAD

**Issue by willifehler** [aruba/aoscx-ansible-collection#114]
Hey there,

I'm trying to use:

https://galaxy.ansible.com/ui/repo/published/arubanetworks/aoscx/docs/aoscx_lag_interface/

I don't see any parameter to configure vlans in the lag_interface.

```
interface lag 2
    description server1
    no shutdown
    no routing
    vlan access 3500
    lacp mode active
    lacp rate fast
    exit
```

Is that currently not implemented yet?

Cheers and many thanks - Willi

**Comment by alagoutte** [comment]
Hi

you need to use aoscx_l2_interface module like for physical interface

**Comment by willifehler** [comment]
Hi @alagoutte,

thank you so much for your feedback. I'll try that.

Cheers - Willi
