### ISSUE TITLE
Set interface to shutdown

### ISSUE THREAD

**Issue by willifehler** [aruba/aoscx-ansible-collection#115]
Hey there,

is it possible to set an interface into shutdown?

I haven't seen any parameter for this.

Cheers - Willi

**Comment by alagoutte** [comment]
You need to look enabled(:disable / false) on aoscx_interface module

**Comment by willifehler** [comment]
Thank you @alagoutte. And thank you so much for this wonderful Collection.

**Comment by tchiapuziowong** [comment]
Hi @willifehler !
Yes as @alagoutte mentioned you'll want to use the aoscx_interface module, an example is as follows:
```
    - name: Disable Interface 1/1/6
      aoscx_interface:
        name: 1/1/6
        enabled: false
```
For some playbook examples on how to use modules you can refer to our workflows repo here:
https://github.com/aruba/aoscx-ansible-workflows

And as always there are documentation on all the modules either[ via Galaxy ](https://galaxy.ansible.com/ui/repo/published/arubanetworks/aoscx/docs/) or as .md files in our [/docs directory](https://github.com/aruba/aoscx-ansible-collection/tree/master/docs).
