### ISSUE TITLE
Set LAG Interface into fallback static

### ISSUE THREAD

**Issue by willifehler** [aruba/aoscx-ansible-collection#116]
Hey there,

I'm trying to put an LAG Interface into the fallback static mode.

```
interface lag 1
    description server1-bond0
    no shutdown
    no routing
    vlan access 3500
    lacp mode active
    lacp fallback-static
```

Is this already implemented?

Cheers - Willi

**Comment by alagoutte** [comment]
Hi @willifehler,

no it is not yet available ! :(

**Comment by willifehler** [comment]
Hey @alagoutte,

thank you so much for your quick feedback. I've implemented a workaround.

Should be fine by now.

Cheers - Willi
