### ISSUE TITLE
aoscx_l2_interface module - removing VLAN doesn't work

### ISSUE THREAD

**Issue by TheDuKeBE** [aruba/aoscx-ansible-collection#118]
After configuring a trunk interface through module aoscx_l2_interface, it is not possible to remove a VLAN.
For example you set:

`vlan_trunks:
    - 1
    - 2
    - 3`

It will deploy correctly. But if you remove VLAN 2 from the list, it is not removed from the switch. A verbose output does show the correct list under vlan_trunks, but it doesn't get applied.

**Comment by alagoutte** [comment]
Hi @TheDuKeBE 

What your full playbook ?

last release of aoscx module ? (and pyaoscx)

What firmware and switch model ?

**Comment by TheDuKeBE** [comment]
An example of the playbook is as follows:

`- name: Configure Interface {{interface}} - router trunk
   aoscx_l2_interface:
     interface: "{{interface}}"
    description: "{{description}}"
    vlan_mode: "{{vlan_mode}}"
    vlan_trunks:
      - 1
      - 40
      - 50
      - 60`

(I also tested without the variables and testing it all out, but same result)

I'm testing this on a 6100 (model JL679A 6100 12G CL4 2SFP+ to be precise) with AOS-CX version PL.10.06.0001. 
The aoscx module is the latest, 4.4.0 indeed. I rolled it back to 4.3.2 at some point, but with the same result.

**Comment by alagoutte** [comment]
May be a good idea to upgrade firmware.. ;-)

I will try with your playbook (you remove after a vlan id and retry but always the vlan_id on the config ?)

**Comment by TheDuKeBE** [comment]
Valid remark about the firmware... :-) I've given it an upgrade now to PL.10.14.1010, but he result remains the same.

Your understanding is correct, you configure via that module vlans 1, 40, 50 & 60 and that works. If for example you then remove vlan 50 from the list, it doesn't remove it from the trunk on the switch. Adding VLANs works, removing doesn't.

**Comment by tchiapuziowong** [comment]
Hi @TheDuKeBE - you'll want to pass in the `state:` parameter and set it to `delete` in order to delete/remove configuration, for example to delete VLAN 50 from the VLAN trunk list, you'd want to do the following:
```
    - name: Delete VLAN 50 from l2 int 1/1/14
      aoscx_l2_interface:
        interface: 1/1/14
        vlan_mode: trunk
        vlan_trunks: [50]
        state: delete

```

The documentation is available within the module as well as in this MD file: https://github.com/aruba/aoscx-ansible-collection/blob/master/docs/aoscx_l2_interface.md

please let me know if you have any issues with this!

**Comment by TheDuKeBE** [comment]
Thanks for the feedback @tchiapuziowong . If I add an additional task for this delete, then it does work.
I find it a bit counter intuitive to be honest, but it does the job. Thanks!

**Comment by alagoutte** [comment]
Hi @tchiapuziowong 

May be when set _state: update_ the module can "update" the list of vlan ? 

After a quick look to code, state: create and update make the same stuff...
