### ISSUE TITLE
arubanetwork.aoscx was not found and no 'owner'

### ISSUE THREAD

**Issue by gpn005** [aruba/aoscx-ansible-collection#2]
While trying to install the arubanetwokrs.aoscx collection, I received 2 below errors. The first saying the content had no owner, the second saying arubanetworks.aoscx was not found on galaxy.

gpn005@NovakG5590:~$ ansible-galaxy collection install arubanetworks.aoscx
- downloading role 'collection', owned by
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
gpn005@NovakG5590:~$ ansible-galaxy collection install arubanetworks.aoscx
- downloading role 'collection', owned by
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
gpn005@NovakG5590:~$ ansible-galaxy collection install arubanetworks.aoscx --ignore-errors
- downloading role 'collection', owned by
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

- downloading role 'aoscx', owned by arubanetworks
 [WARNING]: - arubanetworks.aoscx was NOT installed successfully: - sorry, arubanetworks.aoscx was not found on https://galaxy.ansible.com.

gpn005@NovakG5590:~$ ansible-galaxy collection install arubanetworks.aoscx
- downloading role 'collection', owned by
 [WARNING]: - collection was NOT installed successfully: Content has no field named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by tchiapuziowong** [comment]
Hi @gpn005 !

Can you please post the output of the command `ansible --version` ?

**Comment by gpn005** [comment]
gpn005@NovakG5590:~$ ansible --version
ansible 2.8.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gpn005/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]

Thanks,

-Geoff


Geoff Novak
Sr. Network Engineer
Sirius Computer Solutions
c | (610) 742-7109  o | (215) 695-5112
Geoffrey.Novak@siriuscom.com<mailto:Geoffrey.Novak@siriuscom.com>
[ccnp_routingswitching_sm]

**Comment by tchiapuziowong** [comment]
Collections were introduced into Ansible version 2.9.0 so you'll have to update Ansible in order for the  command to install collections to work 👍

**Comment by gpn005** [comment]
Ok, I thought I had already run an update for everything. I will try again after updating. Thanks for the quick reply.

Thanks,

-Geoff


Geoff Novak
Sr. Network Engineer
Sirius Computer Solutions
c | (610) 742-7109  o | (215) 695-5112
Geoffrey.Novak@siriuscom.com<mailto:Geoffrey.Novak@siriuscom.com>
[ccnp_routingswitching_sm]

**Comment by tchiapuziowong** [comment]
No prob! I'll close the issue for now and if anything comes up just let us know!
