### ISSUE TITLE
Collection not working with ansible 2.10

### ISSUE THREAD

**Issue by targuan** [aruba/aoscx-ansible-collection#3]
Hello,

Some major changes have been introduced to Ansible's API in version 2.10. The aoscx-ansible-collection does not seems to be compatible with this new version.

For instance, the import ```from ansible.module_utils.network.common.utils import to_list``` fails as it as been moved to ```from ansible_collections.ansible.netcommon.plugins.module_utils.network.common.utils import  to_list```

**Comment by tchiapuziowong** [comment]
Hello! We've just published a new version of the collection that should fix this - please install the latest version of the collection and let us know if you're still experiencing issues:
`ansible-galaxy collection install arubanetworks.aoscx -f`

**Comment by narongsak-hewitt** [comment]
I'm glad I saw this! I have been rocking my Ansible journey with CX!!!  I was having some trouble with the modules appearing to work (They don't fail) but there are no changes to my switch.  Going to take the advise here and update my collection.  Thanks!
