### ISSUE TITLE
aoscx-ansible-collection not work

### ISSUE THREAD

**Issue by autotraversa** [aruba/aoscx-ansible-collection#4]
Tried collection on AWX version 15, Ansible Engine 2.10 with SSH and REST API, it doesn't work either one.

**Comment by tchiapuziowong** [comment]
Hello! We've just published a new version of the collection that should fix this - please install the latest version of the collection and let us know if you're still experiencing issues:
`ansible-galaxy collection install arubanetworks.aoscx -f`

**Comment by autotraversa** [comment]
Still not work on AWX, error info as below:
The full traceback is:
Traceback (most recent call last):
  File "/var/lib/awx/.ansible/tmp/ansible-local-17366q573e_pu/ansible-tmp-1603309063.3658378-17373-218564064826250/AnsiballZ_aoscx_vlan.py", line 102, in <module>
    _ansiballz_main()
  File "/var/lib/awx/.ansible/tmp/ansible-local-17366q573e_pu/ansible-tmp-1603309063.3658378-17373-218564064826250/AnsiballZ_aoscx_vlan.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/var/lib/awx/.ansible/tmp/ansible-local-17366q573e_pu/ansible-tmp-1603309063.3658378-17373-218564064826250/AnsiballZ_aoscx_vlan.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_vlan', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, ru…
PLAY RECAP *********************************************************************
6200f_48g_01               : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by autotraversa** [comment]
The collection works with REST API,  not works with SSH

**Comment by tchiapuziowong** [comment]
Hi @autotraversa  can you confirm if the SSH is not working in any platform or only AWX?

**Comment by tchiapuziowong** [comment]
Also make sure the collection ansible.netcommon is installed within AWX container

**Comment by autotraversa** [comment]
Yes, it says it is already installed.

It says """

{
    "module_stdout": "",
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-37416t69wpuun/ansible-tmp-1603588555.9925408-37533-205648963158349/AnsiballZ_aoscx_vlan.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-37416t69wpuun/ansible-tmp-1603588555.9925408-37533-205648963158349/AnsiballZ_aoscx_vlan.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-37416t69wpuun/ansible-tmp-1603588555.9925408-37533-205648963158349/AnsiballZ_aoscx_vlan.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_vlan', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_vlan.py\", line 142, in <module>\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_vlan.py\", line 88, in main\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py\", line 354, in __init__\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py\", line 375, in get_switch_platform\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py\", line 269, in get\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py\", line 171, in get\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Method not found\n",
    "exception": "Traceback (most recent call last):\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-37416t69wpuun/ansible-tmp-1603588555.9925408-37533-205648963158349/AnsiballZ_aoscx_vlan.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-37416t69wpuun/ansible-tmp-1603588555.9925408-37533-205648963158349/AnsiballZ_aoscx_vlan.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/var/lib/awx/.ansible/tmp/ansible-local-37416t69wpuun/ansible-tmp-1603588555.9925408-37533-205648963158349/AnsiballZ_aoscx_vlan.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_vlan', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_vlan.py\", line 142, in <module>\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_vlan.py\", line 88, in main\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py\", line 354, in __init__\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py\", line 375, in get_switch_platform\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py\", line 269, in get\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx.py\", line 171, in get\n  File \"/tmp/ansible_aoscx_vlan_payload_ys79n_yi/ansible_aoscx_vlan_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: Method not found\n",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1,
    "_ansible_no_log": false,
    "changed": false
}
"""

Looks like something to do with Connection ?. I really appreciate your help.

Thank you,
Praveen
________________________________

**Comment by autotraversa** [comment]
Ok, so i didnt read the fine print.

I changed the transport type to REST and it works.

Thank you for your help.

Praveen
________________________________
