### ISSUE TITLE
CLI command time out error

### ISSUE THREAD

**Issue by sebastiaanvduijn** [aruba/aoscx-ansible-collection#43]
Getting an error on instantON Accesspoints (IAP 305 and 205) while executing the following task:

    - name: Execute show run on the Accesspoint
      arubanetworks.aoscx.aoscx_command:
        commands:
          - show run no-encrypt
      register: output

The following error message is thrown:

command timeout triggered, timeout value is 30 secs. I'm only getting this error message on some of the access points while for others it works fine.

I am able to SSH from the ansible host towards the hosts and execute the commands manually with the expected output, I already did compared the configuration with a working one but there is no difference.

Increasing the timeout doesn't help either.

My assumption is an SSH key related issue, however there is not much debugging information available. 

Ansible version: core 2.12.5.post0
Aruba: Latest

**Comment by alagoutte** [comment]
Hi @sebastiaanvduijn 

This module is only for Aruba CX switch not for IAP or InstantON...

**Comment by sebastiaanvduijn** [comment]
I've the same issue with some switches, the command keeps failing with a time out message.

**Comment by tchiapuziowong** [comment]
@sebastiaanvduijn can you provide the switch model and firmware version? As well as an example playbook? I don't believe the command provided in the original post is a valid CX command?
