### ISSUE TITLE
aoscx.facts error 401

### ISSUE THREAD

**Issue by David7660** [aruba/aoscx-ansible-collection#50]
Hello,

I have issue with the module aoscx.facts, I almost always have this issue.

{
  "module_stdout": "",
  "module_stderr": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-local-19yncc_i70/ansible-tmp-1670841483.4422867-27-83626087637210/AnsiballZ_aoscx_facts.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-local-19yncc_i70/ansible-tmp-1670841483.4422867-27-83626087637210/AnsiballZ_aoscx_facts.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-local-19yncc_i70/ansible-tmp-1670841483.4422867-27-83626087637210/AnsiballZ_aoscx_facts.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_facts', init_globals=dict(_module_fqn='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_facts', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_aoscx_facts_payload_2vevgrzz/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py\", line 436, in <module>\n  File \"/tmp/ansible_aoscx_facts_payload_2vevgrzz/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py\", line 350, in main\n  File \"/usr/local/lib/python3.8/site-packages/pyaoscx/pyaoscx_module.py\", line 39, in ensure_connected\n    return fnct(self, *args, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/pyaoscx/device.py\", line 199, in get_firmware_version\n    data = self.get_firmware_info()\n  File \"/usr/local/lib/python3.8/site-packages/pyaoscx/pyaoscx_module.py\", line 39, in ensure_connected\n    return fnct(self, *args, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/pyaoscx/device.py\", line 218, in get_firmware_info\n    raise GenericOperationError(response.text, response.status_code)\npyaoscx.exceptions.generic_op_error.GenericOperationError: 'GENERIC OPERATION ERROR: 401 Authorization Required: Code: 401'\n",
  "exception": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-local-19yncc_i70/ansible-tmp-1670841483.4422867-27-83626087637210/AnsiballZ_aoscx_facts.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-local-19yncc_i70/ansible-tmp-1670841483.4422867-27-83626087637210/AnsiballZ_aoscx_facts.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-local-19yncc_i70/ansible-tmp-1670841483.4422867-27-83626087637210/AnsiballZ_aoscx_facts.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_facts', init_globals=dict(_module_fqn='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_facts', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_aoscx_facts_payload_2vevgrzz/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py\", line 436, in <module>\n  File \"/tmp/ansible_aoscx_facts_payload_2vevgrzz/ansible_aoscx_facts_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_facts.py\", line 350, in main\n  File \"/usr/local/lib/python3.8/site-packages/pyaoscx/pyaoscx_module.py\", line 39, in ensure_connected\n    return fnct(self, *args, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/pyaoscx/device.py\", line 199, in get_firmware_version\n    data = self.get_firmware_info()\n  File \"/usr/local/lib/python3.8/site-packages/pyaoscx/pyaoscx_module.py\", line 39, in ensure_connected\n    return fnct(self, *args, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/pyaoscx/device.py\", line 218, in get_firmware_info\n    raise GenericOperationError(response.text, response.status_code)\npyaoscx.exceptions.generic_op_error.GenericOperationError: 'GENERIC OPERATION ERROR: 401 Authorization Required: Code: 401'\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": false,
  "changed": false
}

  - name: Get vlan facts
    aoscx_facts:
      gather_network_resources:
      - vlans
    register: facts_list

If you have any tips.

Regards,

**Comment by alagoutte** [comment]
What Switch model and firmware ?

last collection release ?

**Comment by David7660** [comment]
Hello,
I'm using it on eve-ng with 10.10 OVA model.
Concerning the collection i'm using the 4.1.1
Regards

**Comment by David7660** [comment]
I close this issue because the error was due to CPU issue on my eve-ng. 

Thanks anyway :)

Regards,
