### ISSUE TITLE
aoscx_upload_config - Option for Uploading Config in CLI Format not working 

### ISSUE THREAD

**Issue by Bernhardvleen** [aruba/aoscx-ansible-collection#51]
I am searching for the correct way to upload config files to switches (6000CX) from aoscx collection with module aoscx_upload_config

First of all one has to wonder if it is really a fact, that CLI files can only be uploaded from a TFTP server and JSON files can be uploaded from a local path on the Ansible Control Node - is that true? If yes, is there a technical reason behind this limitation? 
It is very inconvenient to be forced to using a TFPT server compared to just having the file we want to use in a local path and pushing it directly from there. 

https://github.com/aruba/aoscx-ansible-collection/blob/master/docs/aoscx_upload_config.md

The issue itself is that from the description one has high hopes, that with the option "config_json" we can upload a JSON formatted file and accordingly with "config_file" we can upload a CLI formatted file. 

config_json:
    description: "JSON file name and path for locally uploading configuration,
      only JSON version of configuration can be uploaded"
    type: str
    required: false
  config_file:
    description: "File name and path for locally uploading configuration,
      will be converted to JSON,
      only JSON version of configuration can be uploaded"
    type: str
    required: false

But uploading a CLI file results in an error:

 return _default_decoder.decode(s)\n  File \"/usr/lib/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

It seems that the module tries to read JSON?

Maybe I am doing it wrong? I don't think that it matters how the CLI File is structured, since the error message seems to say that JSON is expected / is to be decoded.

Another issue is regarding the examples in aoscx_upload_config.md: all examples show "remote_config_file_tftp_path" but "Copy Running Config from local JSON file as JSON" should use "config_json", or not? Please let me know what is what, many thanks in advance and thanks for maintaining the Aruba collections - to be able to use ansible for central configuration of Aruba Switches really is a great thing!

Please also elaborate on this option: 
config_name:
    description: "Config file or checkpoint to be uploaded to.
the mention of the fact that when using TFTP only startup-config and running-config is allowed, seems to be incorrect - I was not able to use any of the checkpoint names to upload a JSON config from a local path - only startup-config and running-config was working as value for config_name in my tests - exactly how it is described as when using TFTP..

**Comment by alagoutte** [comment]
Hi @Bernhardvleen 

It think, it is a limitation of API (only support json file)

you can look on switch API swagger https://switchip/api/v10.08/#/Configuration/put_configs__name_

and i think the md need to be update (@tchiapuziowong ) it is not the same example on module file -> https://github.com/aruba/aoscx-ansible-collection/blob/27e9545f69870b4993e855e95469fc729dccd801/plugins/modules/aoscx_upload_config.py#L61

you can use also the ansible cli command to get example

`ansible-doc -t module arubanetworks.aoscx.aoscx_upload_config
`

**Comment by tchiapuziowong** [comment]
Hi @Bernhardvleen - @alagoutte is correct in that this is a limitation with the API - if you'd rather use an alternative method for uploading a CLI formatted configuration you can use our SSH module to execute CLI commands. We have an example using firmware but the same can be used for a configuration as seen in [this workflow](https://github.com/aruba/aoscx-ansible-workflows/blob/master/copy_config_using_cli_prompt.yml). 

You can also use the `src:` parameter to provide a local file:

```
    - name: configure switch using local CLI file
      aoscx_config:
        src: /path/to/generated_config.txt
```

**Comment by Bernhardvleen** [comment]
Hi @alagoutte  -  Happy New Year to all of you! 🎉🎉🎉🎉🎉

thank you for the idea with the test option for ansible-doc - after executing the command you showed, one can find the following:

- remote_config_file_tftp_path
        TFTP server address and path for uploading configuration, can be JSON or CLI format,
        must be reachable through provided vrf.
        [Default: (null)]
        type: str

this is the same we can find in md as well - it hints that a config file in CLI format can be used - does the TFTP option not use the API? I can not understand where this restriction comes from. 

Creating a config file and convert it from a CLI form to JSON form is a pain. The option of just using config files that where used until now (i.e. in CLI form) is very desirable in my opinion. Not having it is a huge deterrent for the adoption of using Ansible  for Aruba Switch configuration and thus a waste of your efforts so far.. 

I can confirm that the uploading of CLI and JSON formatted config files works, if the files come from a TFTP server.

**Comment by Bernhardvleen** [comment]
> Hi @Bernhardvleen - @alagoutte is correct in that this is a limitation with the API - if you'd rather use an alternative method for uploading a CLI formatted configuration you can use our SSH module to execute CLI commands. We have an example using firmware but the same can be used for a configuration as seen in [this workflow](https://github.com/aruba/aoscx-ansible-workflows/blob/master/copy_config_using_cli_prompt.yml).
> 
> You can also use the `src:` parameter to provide a local file:
> 
> ```
>     - name: configure switch using local CLI file
>       aoscx_config:
>         src: /path/to/generated_config.txt
> ```

thank you @tchiapuziowong - I can work around the limitation.

regarding using local filesystem path for uploading config files, using this play unfortunately results in error:

fatal: [aoscx_1]: FAILED! => {"changed": false, "err": "Method not found", "msg": "unable to retrieve current config"}

---
- name:
  hosts: all
  collections:
    - arubanetworks.aoscx
  vars:
    path: './running-config.cli'
  tasks:
  - name: Upload Running Config from local Filesystem as CLI file
    aoscx_config:
      src: "{{ path }}"

am I doing it wrong? The file does exist within the same folder as the play. Does the error message mean, that it can not read the current config to check if there are differences? 

thanks a lot for you help!

**Comment by alagoutte** [comment]
@Bernhardvleen  do you have try to use full path ?

**Comment by tchiapuziowong** [comment]
@Bernhardvleen since this play is using the SSH modules you'll need to ensure your `ansible_connection` variable is set to `network_cli` for the proper connection. You can do this in your playbook like so:
```
- hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: False
  vars:
    path: './running-config.cli'
    ansible_connection: network_cli        
  tasks:
    - name: Upload Running Config from local Filesystem as CLI file
      aoscx_config:
        src: "{{path}}"

```

**Comment by Bernhardvleen** [comment]
@tchiapuziowong  thank you for the hint, you are correct of course, I had not set the connection properly for the test.

**Comment by tchiapuziowong** [comment]
Module documentation has been updated: https://github.com/aruba/aoscx-ansible-collection/blob/master/docs/aoscx_upload_config.md
