### ISSUE TITLE
Upload firmware to AOSCX 6200 switch does not work

### ISSUE THREAD

**Issue by prietonoble** [aruba/aoscx-ansible-collection#71]
Hi, have read and tried many things but I just can't seem to get aoscx_upload_firmware to work. The switch is 6200F and it basically fails with the following stack trace. I can see that its returning connection refused but I don't understand why.

Inventory (hostvars):

ansible_host: xxx.xx.xx.xx
nodeid: 395
vendor: HPE
ansible_acx_no_proxy: 'True'
ansible_connection: arubanetworks.aoscx.aoscx
ansible_httpapi_use_ssl: 'True'
ansible_httpapi_validate_certs: 'False'
ansible_network_os: arubanetworks.aoscx.aoscx
ansible_user: username
ansible_aoscx_validate_certs: 'False'

Module errors:

{
  "module_stdout": "",
  "module_stderr": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-local-24_gv6gl13/ansible-tmp-1681737261.5509152-51-195649211638486/AnsiballZ_aoscx_upload_firmware.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-local-24_gv6gl13/ansible-tmp-1681737261.5509152-51-195649211638486/AnsiballZ_aoscx_upload_firmware.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-local-24_gv6gl13/ansible-tmp-1681737261.5509152-51-195649211638486/AnsiballZ_aoscx_upload_firmware.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_upload_firmware', init_globals=dict(_module_fqn='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_upload_firmware', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_aoscx_upload_firmware_payload_uj7d527i/ansible_aoscx_upload_firmware_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_upload_firmware.py\", line 195, in <module>\n  File \"/tmp/ansible_aoscx_upload_firmware_payload_uj7d527i/ansible_aoscx_upload_firmware_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_upload_firmware.py\", line 115, in main\n  File \"/tmp/ansible_aoscx_upload_firmware_payload_uj7d527i/ansible_aoscx_upload_firmware_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx_pyaoscx.py\", line 82, in get_pyaoscx_session\n  File \"/tmp/ansible_aoscx_upload_firmware_payload_uj7d527i/ansible_aoscx_upload_firmware_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx_pyaoscx.py\", line 47, in __init__\n  File \"/tmp/ansible_aoscx_upload_firmware_payload_uj7d527i/ansible_aoscx_upload_firmware_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: HTTPSConnectionPool(host='172.28.50.4', port=443): Max retries exceeded with url: /rest/v10.04/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fce5335ddf0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
  "exception": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-local-24_gv6gl13/ansible-tmp-1681737261.5509152-51-195649211638486/AnsiballZ_aoscx_upload_firmware.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-local-24_gv6gl13/ansible-tmp-1681737261.5509152-51-195649211638486/AnsiballZ_aoscx_upload_firmware.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-local-24_gv6gl13/ansible-tmp-1681737261.5509152-51-195649211638486/AnsiballZ_aoscx_upload_firmware.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_upload_firmware', init_globals=dict(_module_fqn='ansible_collections.arubanetworks.aoscx.plugins.modules.aoscx_upload_firmware', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.9/runpy.py\", line 225, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_aoscx_upload_firmware_payload_uj7d527i/ansible_aoscx_upload_firmware_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_upload_firmware.py\", line 195, in <module>\n  File \"/tmp/ansible_aoscx_upload_firmware_payload_uj7d527i/ansible_aoscx_upload_firmware_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_upload_firmware.py\", line 115, in main\n  File \"/tmp/ansible_aoscx_upload_firmware_payload_uj7d527i/ansible_aoscx_upload_firmware_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx_pyaoscx.py\", line 82, in get_pyaoscx_session\n  File \"/tmp/ansible_aoscx_upload_firmware_payload_uj7d527i/ansible_aoscx_upload_firmware_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/module_utils/aoscx_pyaoscx.py\", line 47, in __init__\n  File \"/tmp/ansible_aoscx_upload_firmware_payload_uj7d527i/ansible_aoscx_upload_firmware_payload.zip/ansible/module_utils/connection.py\", line 200, in __rpc__\nansible.module_utils.connection.ConnectionError: HTTPSConnectionPool(host='172.28.50.4', port=443): Max retries exceeded with url: /rest/v10.04/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fce5335ddf0>: Failed to establish a new connection: [Errno 111] Connection refused'))\n",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": null,
  "changed": false
}

**Comment by tchiapuziowong** [comment]
Hi @prietonoble - we do have a known issue regarding the 6xxx series and the upload firmware module that we're tracking through this issue: https://github.com/aruba/aoscx-ansible-collection/issues/52

Although it's not the EXACT message you might be receiving- can you confirm whether or not you're able to use other modules with the collection such as [aoscx_vlan](https://github.com/aruba/aoscx-ansible-collection/blob/master/plugins/modules/aoscx_vlan.py) or [aoscx_interface](https://github.com/aruba/aoscx-ansible-collection/blob/master/plugins/modules/aoscx_interface.py) ?

**Comment by prietonoble** [comment]
Hi,

I am able to run other modules but let me check the ones you suggest such
as aoscx_vlan or aoscx_interface. I’ll let you know once i test this
morning.

Thanks for the prompt response!

**Comment by tchiapuziowong** [comment]
We've just uploaded a new version of the collection that addresses this issue- please ensure to install the latest version of the collection, pyaoscx, and pycurl with the following commands:
`pip install pycurl`

`pip install pyaoscx --upgrade`

`ansible-galaxy collection install arubanetworks.aoscx -f`

**Comment by prietonoble** [comment]
Hi,

Followed your instructions and we’re making progress but I’m now getting
this error message. Tried aosxc_vlan to add a vlan and it worked correctly.
Any ideas?

The full traceback is:

  File
"/tmp/ansible_aoscx_upload_firmware_payload_8t5q_o79/ansible_aoscx_upload_firmware_payload.zip/ansible_collections/arubanetworks/aoscx/plugins/modules/aoscx_upload_firmware.py",
line 171, in main

  File
"/home/tfgadmin/myvenv/lib64/python3.9/site-packages/pyaoscx/device.py",
line 565, in upload_firmware

    result = self.upload_firmware_local(

  File
"/home/tfgadmin/myvenv/lib64/python3.9/site-packages/pyaoscx/device.py",
line 518, in upload_firmware_local

    success = utils.file_upload(

  File
"/home/tfgadmin/myvenv/lib64/python3.9/site-packages/pyaoscx/utils/util.py",
line 309, in file_upload

    raise GenericOperationError(

fatal: [TOG_SW01]: FAILED! => {

    "changed": false,

    "invocation": {

        "module_args": {

            "firmware_file_path": "/tmp/ArubaOS-CX_6200_10_10_1040.swi",

            "partition_name": "primary",

            "remote_firmware_file_path": null,

            "vrf": null,

            "wait_firmware_upload": false

       }

    },

    "msg": "'GENERIC OPERATION ERROR: 401 Authorization Required: Code:
401'"

}

**Comment by tchiapuziowong** [comment]
401 Authorization Required might be a login error but you're saying that the same device works with the same inventory using a different module i.e. aoscx_vlan?

**Comment by prietonoble** [comment]
Correct. Other modules work as well such as aoscx_command etc.

**Comment by prietonoble** [comment]
Out of curiosity. Is there another way i can upload a firmware file to the
switch? I tried calling sftp with aoscx_command but I can’t seem to get it
to work.

**Comment by tchiapuziowong** [comment]
@prietonoble when using the REST API modules i.e. aoscx_upload_firmware and aoscx_vlan please ensure your ansible_connection is set to arubanetworks.aoscx.aoscx 

And yes we have the option to use aoscx_command for sftp - we have an example on our workflows repository here: https://github.com/aruba/aoscx-ansible-workflows/blob/master/copy_config_using_cli_prompt.yml

**Comment by prietonoble** [comment]
Hi,

Yes, I have a hostvar setup which sets ansible_connection to
arubanetworks.aoscx.aoscx.

Cool! Thanks for that, i'm having a look at it now.

**Comment by tchiapuziowong** [comment]
@prietonoble can you provide a sample of what your task looks like in your playbook?

**Comment by prietonoble** [comment]
Hi,

This works for me.

- name: upload via SFTP

      vars:

        - ansible_command_timeout: 240

      aoscx_command:

        commands:

          - command: "copy sftp://{{ sftp_username }}@<IP>/
***@***.***/>{{ fw_image }} secondary vrf default"

            check_all: True

            prompt:

              - '.*\(y\/n\)\?.*'

              - '.*\(yes\/no\/\[fingerprint\]\)\?.*'

              - '.*Password:.*'

            answer:

              - 'y'

              - 'yes'

              - '{{ sftp_password }}'
