### ISSUE TITLE
aoscx_l2_interface: Internal service error. Code 500

### ISSUE THREAD

**Issue by smirlach** [aruba/aoscx-ansible-collection#75]
Hello,

i'm trying to add a VLAN in mode trunk to an interface and get the error:
`pyaoscx.exceptions.generic_op_error.GenericOperationError: 'GENERIC OPERATION ERROR: Internal service error.\n: Code: 500`

The task i'm trying to execute is:
```yaml
  - name: Add VLAN configuration to inside_channel
    arubanetworks.aoscx.aoscx_l2_interface:
      interface: lag1
      vlan_mode: trunk
      vlan_trunks: 2005
```

The full error message i get is:
```
The full traceback is:
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pyaoscx/pyaoscx_factory.py", line 132, in interface
    interface_obj.create()
  File "/Users/user/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pyaoscx/pyaoscx_module.py", line 40, in ensure_connected
    return fnct(self, *args, **kwargs)
  File "/Users/user/.pyenv/versions/3.9.6/lib/python3.9/site-packages/pyaoscx/interface.py", line 467, in create
    raise GenericOperationError(response.text, response.status_code)
pyaoscx.exceptions.generic_op_error.GenericOperationError: 'GENERIC OPERATION ERROR: Internal service error.\n: Code: 500'
```

Can someone please assist me?

Best regards

**Comment by alagoutte** [comment]
Hi,

What switch model ?

What release of Aruba CX module ? and plugins ?

**Comment by tchiapuziowong** [comment]
Hi @smirlach , At this time LAG interface isn't supported with the aoscx_l2_interface module but we're preparing a release that will include support of this feature within the very near future - I will mark this as an enhancement and update it when the release is public. Thank you for your patience!

**Comment by tchiapuziowong** [comment]
@smirlach can you share the switch firmware/model you're using? As well as the desired CLI configuration you're trying to achieve? When I attempt to configure VRRP on an individual interface that's L2 (no routing) I receive an error stating that VRRP cannot be configured on an L2 interface, which could be the cause of this error...

```
Access-6200-01(config-if)# vrrp 2 address-family ipv4
Cannot configure VRRP on an L2 interface.
Access-6200-01(config-if)# routing
Access-6200-01(config-if)# show run curr
interface 1/1/14
    no shutdown
    routing
    exit
Access-6200-01(config-if)#  vrrp 2 address-family ipv4
Access-6200-01(config-if-vrrp)# show run curr
interface 1/1/14
    vrrp 2 address-family ipv4
```

**Comment by tchiapuziowong** [comment]
@smirlach can you provide your VLAN & LAG configuration? Omitting or changing sensitive data

**Comment by tchiapuziowong** [comment]
Okay thank you for providing the config! I was able to confirm that with the upcoming release that supports LAG will work with this use case - I'll update this issue once the release is public and have you verify the issue is no longer seen!

**Comment by alagoutte** [comment]
> Okay thank you for providing the config! I was able to confirm that with the upcoming release that supports LAG will work with this use case - I'll update this issue once the release is public and have you verify the issue is no longer seen!

can be close ? the release 4.5 add support of LAG ?
