### ISSUE TITLE
How to run show command over REST API

### ISSUE THREAD

**Issue by tomdeppe** [aruba/aoscx-ansible-collection#9]
I'm looking for a module that uses REST API connection to run a show command, such as show mac-address-table.
Similar to the aoscx_command, however using the REST API instead of SSH.  Is there a way to do this?
Thank you

**Comment by tchiapuziowong** [comment]
Hi @tomdeppe - we currently do not have any "show"command support via REST-API, we have support for the GET method for all our resources. We do have support for gathering facts using the [aoscx_facts](https://github.com/aruba/aoscx-ansible-collection/blob/master/docs/aoscx_facts.md) as well as have [NAPALM](https://developer.arubanetworks.com/aruba-aoscx/docs/getting-started-with-napalm) support which can be called using Ansible-
